### ISSUE TITLE
Rename tooltips

### ISSUE THREAD

**Issue by MysteryFlask** [Potato-Development/notepad-sharp#5]
Currently, when hovering over these buttons:

![image](https://github.com/Potato-Development/notepad-sharp/assets/76215428/b0ec98aa-ca77-4a85-b6e2-d03b7d8c94d7)

the tooltips read 'toolStripButton1, toolStripButton2...'. These should be changed to say whatever the button being hovered over actually does to improve user experience.

**Comment by so1maru** [comment]
This issue has been addressed. A fix will come soon.

**Comment by so1maru** [comment]
New notepad-sharp is out with added toolbar tooltips:

![image](https://github.com/Potato-Development/notepad-sharp/assets/119129834/b4b391d2-aa87-4c54-9f2a-70685083de47)
