### ISSUE TITLE
Filepath and name in titlebar

### ISSUE THREAD

**Issue by so1maru** [Potato-Development/notepad-sharp#6]
open filepath and name should be shown in title bar before the application name:

![image](https://github.com/Potato-Development/notepad-sharp/assets/119129834/c51d11f2-6fe3-43d3-afcf-a4a790b708c0)

**Comment by MysteryFlask** [comment]
good idea :]

**Comment by so1maru** [comment]
This issue is being resolved now. A new build will be out in approx 30 mins.

**Comment by so1maru** [comment]
![image](https://github.com/Potato-Development/notepad-sharp/assets/119129834/c882e7d8-3e14-419d-92a9-c6e1d2ef31be)

Issues have been resolved! Check the changelog: https://github.com/orgs/Potato-Development/discussions/10 for more info!

**Comment by edamame-maru** [comment]
.

**Comment by so1maru** [comment]
.
